export const DOG_BREEDS = [
  'Beagle',
  'Border Collie',
  'Boxer',
  'Bulldog',
  'Chihuahua',
  'Cocker Spaniel',
  'Dachshund',
  'Doberman',
  'French Bulldog',
  'German Shepherd',
  'Golden Retriever',
  'Great Dane',
  'Husky',
  'Jack Russell Terrier',
  'Labrador Retriever',
  'Maltese',
  'Pitbull',
  'Poodle',
  'Pomeranian',
  'Rottweiler',
  'Schnauzer',
  'Shih Tzu',
  'Weimaraner',
  'Yorkshire Terrier',
  'Mixed / Rescue',
  'Other',
] as const;

export type DogBreed = (typeof DOG_BREEDS)[number];
